version: "3.9"

services:
  financial_server:
    # image: docker.io/sebastian992/auth_server
    build: .
    env_file:
      - .env
    ports:
      - "8084:8084"
    depends_on:
      - financial_database
  financial_database:
    image: postgres:14
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_DB}
    env_file:
      - .env
    volumes:
      - financial_volumn:/var/lib/postgres
    command: -p 5435
    expose:
      - 5435
    ports:
      - 5435:5435

volumes:
  financial_volumn:
